### ISSUE TITLE
SEO Title Detection

### ISSUE THREAD

**Issue by connorwhitman** [LiamMartens/sanity-plugin-seo-tools#16]
With the SEO title set (and successfully validating with the "Keyphrase found in page title" response) the plugin also returns "Be sure to include an SEO title on your page"

**Comment by markwtierney** [comment]
@LiamMartens we're facing the same issue. Any idea when this will be fixed so that we could start using the plugin?

**Comment by LiamMartens** [comment]
@markwtierney what kind of config are you using? Is it scraping the site or are you injecting it using the data functions?

**Comment by markwtierney** [comment]
@LiamMartens we're scraping but we have also tried injecting with the same result.

**Comment by LiamMartens** [comment]
Published a new version that addresses this issue
