### ISSUE TITLE
Add option to make fields required

### ISSUE THREAD

**Issue by masives** [LiamMartens/sanity-plugin-seo-tools#17]
Is there an option to makes fields required, meaning you can't publish a document without seo title and seo metadescription. I find that content authors I'm working on rely heavily on missing fields that I suggest to them, meaning that when the field isn't red they might forget to fill it in.

**Comment by LiamMartens** [comment]
Added new configuration options to make SEO fields required.
Following options can be added in `config/seo-tools.json`
```
{
    "focus_keyword_required": false, // makes the focus_keyword field required
    "focus_synonyms_required": false, // makes the focus_synonyms field required
    "seo_title_requied": false, // makes the seo_title field required
    "meta_description_required": false // makes the meta_description field required
}
```
