### ISSUE TITLE
Arbitrary URL-patterns

### ISSUE THREAD

**Issue by simen** [LiamMartens/sanity-plugin-seo-tools#2]
I love this! Some sites might not follow the `baseUrl + slug` pattern of urls. Would it make sense to optionally be able to supply a `pageUrl(doc) { . . . }` function rather than the baseUrl and slug functions separately?

**Comment by LiamMartens** [comment]
Don't think this would necessarily make sense since in the end every site uses a base url and slug pattern in a way that they have a certain domain and path structure. You can reopen if you have a specific example where this would be inherently useful
