### ISSUE TITLE
CSS hard coded and doesn't support dark theme in Sanity Studio

### ISSUE THREAD

**Issue by etuned** [LiamMartens/sanity-plugin-seo-tools#22]
As I am styling the sanity studio in a dark theme, I noticed that the css is hard coded. Is there a way to override it so I can use a dark theme in the studio?

**Comment by LiamMartens** [comment]
I switched to CSS variables, let me know if that is enough for your dark theme use case.

```
:root {
    --seo-tools--color--dark: #000;
    --seo-tools--color--light: #fff;
    --seo-tools--color--gray: #f1f1f1;
    --seo-tools--color-accent: #156dff;
}
```

**Comment by etuned** [comment]
Thanks for the quick change and response. This update fixed the issue, namely that color was not defined. I should note that having the seo-tools.json is required as the absence of the config in sanity breaks the build.  The styles work for a dark theme now, but if one wants to override the styling, is it possible to utilize the sanity part system, or module overrides? Loving the plugin, and my client is very happy.
