### ISSUE TITLE
Module not found: Error: Can't resolve 'config:seo-tools'

### ISSUE THREAD

**Issue by markwtierney** [LiamMartens/sanity-plugin-seo-tools#25]
@LiamMartens 
We're getting this error are your latest update.

Error in ./node_modules/sanity-plugin-seo-tools/lib/schema/index.js
Module not found: Error: Can't resolve 'config:seo-tools' in '/Users/___/node_modules/sanity-plugin-seo-tools/lib/schema'
 @ ./node_modules/sanity-plugin-seo-tools/lib/schema/index.js 3:13-40
 @ ./node_modules/sanity-plugin-seo-tools/lib/schema (all:part:@sanity/base/schema-type)
 @ ./schemas/schema.js (part:@sanity/base/schema)

**Comment by LiamMartens** [comment]
Hm sanity should actually auto-create this for you. It is because it is now using a sanity config file - can be created in the `config` folder and should be called `seo-tools.json`.

**Comment by markwtierney** [comment]
Hi Liam, that’s no where to be found. What would the contents of that file be?

**Comment by Rondieli** [comment]
@markwtierney  

```
### Can't resolve "config:seo-tools"
In v1.1.0 we added a config file. To get rid of this error when upgrading an instance simply add a file called `seo-tools.json` to your `config` folder and set it to an empty object `{}`.
```
(From readme)

Would be nice to see if there are any options

**Comment by markwtierney** [comment]
Thanks. Worked.

Mark

**Comment by LiamMartens** [comment]
Ah I see what happened now. Normally Sanity auto-creates this config file for you but I forgot to include the default on in the npm package. I updated the package now to include the auto-write the default one
