### ISSUE TITLE
Javascript console errors for v1.1.0

### ISSUE THREAD

**Issue by markwtierney** [LiamMartens/sanity-plugin-seo-tools#27]
Hi,
We're getting JS console errors for v1.1.0 - see attached. 
Any idea what could be causing these?

<img width="1016" alt="Screenshot 2021-02-10 at 20 59 36" src="https://user-images.githubusercontent.com/5812544/107564662-fd37b700-6be2-11eb-835e-80c885af03e3.png">
<img width="1019" alt="Screenshot 2021-02-10 at 20 59 47" src="https://user-images.githubusercontent.com/5812544/107564667-ff9a1100-6be2-11eb-8fb9-47f4fe5448a1.png">

**Comment by markwtierney** [comment]
@LiamMartens just wondering if you had a chance to look at this?

**Comment by LiamMartens** [comment]
Looks like some internal changes in Sanity because of making use of some of their internal components I need to make sure I keep up with it; I released v2.0.0 now which revises the UI to use `@sanity/ui` and also resolves these errors. Let me know if it's all good :+1:

**Comment by viking11** [comment]
I had exact same error, just updated to v2.0.0, and installed @sanity/ui. Error is gone 👍
