### ISSUE TITLE
is there a way to customize the schema?

### ISSUE THREAD

**Issue by nirjan-dev** [LiamMartens/sanity-plugin-seo-tools#28]
Thank you for this awesome plugin 🙏 

Is there a way to customize the schema for seo tools currently, or are there any plans to make it more customizable in the future?

We want to use a different label for the seo fields in our sanity studio

SEO Title > Change to > 'Google Headline (Please Frontload SEO Terms)'
Meta description > Change to > 'Google Story Description (Please pack with SEO terms)'

**Comment by LiamMartens** [comment]
A little late - but it is now possible to do this from v2.2.0 on ([How to implement](https://github.com/LiamMartens/sanity-plugin-seo-tools#available-parts-for-implementation))
