### ISSUE TITLE
This plugin needs to be re-licensed under GPLv3

### ISSUE THREAD

**Issue by nilsnh** [LiamMartens/sanity-plugin-seo-tools#3]
Hi there,

Thanks for building this plugin. :)

I just noticed that this plugin is licensed under MIT, but depends on [yoastseo which uses GPLv3](https://www.npmjs.com/package/yoastseo). This plugin needs to be re-licensed under [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) if it wants to rely on yoastseo. 

[Relevant StackOverflow answer](https://opensource.stackexchange.com/a/1641).

**Comment by LiamMartens** [comment]
Ah you're right, updated.
