### ISSUE TITLE
fetchRemote: false

### ISSUE THREAD

**Issue by danny-waite** [LiamMartens/sanity-plugin-seo-tools#40]
Just checking out this plugin on a Gatsby based site.  It seems odd that the plugin is fetching a remote version of the document since it won't yet be available when first creating.  Am I missing something? 

Hence, do you have an example of `fetchRemote: false` where the plugin reads from a document with a block array field?

**Comment by LiamMartens** [comment]
You would need to provide the additional parameters as described in the V2 [README](https://github.com/LiamMartens/sanity-plugin-seo-tools/blob/e13116bb1119ad430cbe278edf17dfc8c1fda5a8/README.md). This comes down to providing the `content`, `title`, `description` and `locale` fields.

In V3 this works slightly differently, but it comes down to the same thing as can be seen in the V3 [README](https://github.com/LiamMartens/sanity-plugin-seo-tools/blob/e13116bb1119ad430cbe278edf17dfc8c1fda5a8/README.md)
