### ISSUE TITLE
GET-request triggering every ~3s

### ISSUE THREAD

**Issue by gabrielwallin** [LiamMartens/sanity-plugin-seo-tools#41]
We've implemented this plugin in out NextJS + Sanity app, and everything seems to work smoothly. One issue we've found, however, is that the `useEffect` that calls `performYoastCheck()`seems to trigger every 2 or 3 seconds, leaving out network log full of requests. Is this a known bug, or have we just messed up the implementation on our end? 

We haven't done anything beyond what's suggested in the readme

https://user-images.githubusercontent.com/22050503/143859270-3162681f-7ee6-4ece-9a66-feb6f3d0a18d.mov

**Comment by LiamMartens** [comment]
Resolved in newer version
