### ISSUE TITLE
Unknown type: seo-tools.

### ISSUE THREAD

**Issue by schellenbergk** [LiamMartens/sanity-plugin-seo-tools#63]
Not sure what the issue is but I've followed installation instructions and I keep getting this error.

Do I need to manually register `seo-tools` schema type?

**Comment by schellenbergk** [comment]
I did follow the README instructions, and I'm still getting the error when I visit Sanity admin.

1. `sanity install seo-tools`
2.  Added the pane
3.  `Unknown type: seo-tools`

**Comment by hanshenrik** [comment]
I also got this error, because I first followed the old guide, and I therefore had added something like this to one of my documents:
```
{
  name: "seo",
  title: "SEO",
  type: "seo-tools",
  options: { ... }
}
```
By removing this, the `Unknown type: seo-tools` error went away ✌️
