### ISSUE TITLE
CORS Setup

### ISSUE THREAD

**Issue by 3200creative** [LiamMartens/sanity-plugin-seo-tools#8]
Thanks for build this!

I'm stuck on an install step:

Step 3: Make sure to enable CORS for the Sanity domain otherwise the plugin won't be able to fetch your content.

I've got http://localhost:3333 added to CORS Origins however the Audit tool is still getting stuck on 'Performing seo audit...'

It looks like it's trying to audit and getting stopped due to CORS.

Console shows warning: 'A cookie associated with a cross-site resource at https://api.sanity.io/ was set without the `SameSite` attribute.'

**Comment by ovsw** [comment]
I had to add an access-control-allow-origin header on the actual live website on which the scraping is being done.

Since I use netlify, I just added a netlify.toml to my app with:
```
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
``` 
* should of course be replaced with your sanity studio domain, this is just for trouble-checking.

**Comment by LiamMartens** [comment]
As @ovsw you should add CORS headers to the domain you set up for crawling,
however you could also disable the crawling altogether if you set up all content helper methods.

```
  fetchRemote: false <-- add this in plugin configuration and add all content helper methods for the analysis. Feel free to reopen if you still have issues.
```
