### ISSUE TITLE
Poor SPA support

### ISSUE THREAD

**Issue by roffelsaurus** [LiamMartens/sanity-plugin-seo-tools#9]
As it stands now, the remote html is just statically parsed. This makes it so only 100% static/ssr stuff will work correctly. For example gatsby with react-helmet will not work as that gives browser-side inserted meta tags.
Googlebot works for SPA, so this is kind of a SEO mismatch.

To fix this we should switch to some kind of headless chromium. There is also a couple of functions that should check for promises returned. 

I am gonna work on this tomorrow. Would you like me to create a pull request for this? probably gonna be hard to avoid slight breaking changes.

**Comment by franzwilhelm** [comment]
@roffelsaurus did you work on this?
